version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_lab
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demopassword
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      
      - ./init-scripts:/docker-entrypoint-initdb.d:ro

      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer-lab 
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
