name: Automate Database Lab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Start Docker Compose
      run: |
        docker-compose up -d
      working-directory: ./  # Adjust if docker-compose.yaml is in a subdirectory

    - name: Wait for database to be ready
      run: |
        until docker exec $(docker ps -q -f name=database-lab) mysqladmin ping --silent; do
          echo "Waiting for database to be ready..."
          sleep 5
        done

    - name: Run initialization scripts
      run: |
        docker exec $(docker ps -q -f name=database-lab) mysql -u root -prootpassword < /init-scripts/01-create-table.sql
        docker exec $(docker ps -q -f name=database-lab) mysql -u root -prootpassword < /init-scripts/02-seed-data.sql
