name: Deploy SQL Scripts

on:
  push:
    branches:
      - main  # Trigger this on a push to the main branch
  pull_request:
    branches:
      - main  # Trigger this on a PR to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up MySQL (or the relevant database client)
      - name: Set up MySQL
        uses: docker://mysql:latest
        with:
          entrypoint: /bin/bash
          args: "-c 'while ! mysqladmin ping --silent; do sleep 1; done'"

      # Run the SQL script for creating the table
      - name: Run create table SQL script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < ./init-scripts/create_table.sql

      # Run the SQL script for inserting data
      - name: Run insert data SQL script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < ./init-scripts/insert_data.sql
