name: Deploy MySQL and Adminer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: Start Services with Docker Compose
        run: |
          docker compose up -d

      - name: Verify Running Containers
        run: |
          docker ps -a

      - name: Wait for MySQL to be Ready
        run: |
          sleep 30
          docker exec mysql_lab mysqladmin ping -h localhost -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }}

      - name: Run Database Initialization Script (Optional)
        run: |
          docker exec mysql_lab mysql -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "SHOW DATABASES;"

      - name: Stop Containers (Optional)
        if: always()
        run: |
          docker compose down
