name: MySQL & Adminer CI
on: [push]

jobs:
  test-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: demo_db
          MYSQL_USER: demouser
          MYSQL_PASSWORD: demopassword
        ports:
          - 3307:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Test MySQL Connection
        run: |
          mysql -h 127.0.0.1 -P 3307 -u demouser -pdemopassword -e "SHOW DATABASES;"
