name: Database Insertion Pipeline

on:
  push:
    branches:
      - main  # You can specify a branch or event that triggers the pipeline

jobs:
  db-insertion:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up MySQL client
      - name: Set up MySQL client
        run: sudo apt-get install mysql-client

      # Step 3: Run SQL script to insert data into the database
      - name: Insert data into database
        run: |
          mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} <<EOF
          INSERT INTO employees (name, role) VALUES
          ('Altin', 'Devops Engineer'),
          ('Enis', 'Developer');
          EOF
