name: Docker Compose Deploy

on:
  push:
    branches:
      - main  # Adjust branch name to your default branch
  pull_request:
    branches:
      - main  # Adjust to the target branch for PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
          
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Containers
        run: |
          # Ensure Docker Compose is available
          sudo apt-get update
          sudo apt-get install -y docker-compose

          # Set up environment variables from GitHub secrets
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

          # Build and start the services
          docker-compose -f docker-compose.yml up -d

      - name: Run healthcheck for MySQL service
        run: |
          docker exec mysql_lab mysqladmin ping -h localhost -p${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Clean up Docker containers
        run: |
          docker-compose down
